/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package memocardbuilder;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {

    public static void main (String... args) {

        launch(args);

    }


    @Override
    public void start(Stage primaryStage) throws Exception {

        FXMLLoader fxmll = new FXMLLoader(getClass().getResource("scenes/MainScene.fxml"),
                Strings.getStrings());

        Parent root = fxmll.load();
        primaryStage.setScene(new Scene(root));
        primaryStage.setTitle(Strings.get("app_name"));
        primaryStage.show();
    }
}
